//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACPersonne", ConfigurationName="Bibliotheque.Proxies.ClsIFACPersonne")]
    public interface ClsIFACPersonne
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACPersonne/ClsIFACPersonne/SelectAllPersonne", ReplyAction="COUCHEIFAC/ClsIFACPersonne/ClsIFACPersonne/SelectAllPersonneResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOPersonne> SelectAllPersonne();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACPersonne/ClsIFACPersonne/SelectAllPersonne", ReplyAction="COUCHEIFAC/ClsIFACPersonne/ClsIFACPersonne/SelectAllPersonneResponse")]
        System.IAsyncResult BeginSelectAllPersonne(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOPersonne> EndSelectAllPersonne(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACPersonneChannel : Bibliotheque.Proxies.ClsIFACPersonne, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACPersonneClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACPersonne>, Bibliotheque.Proxies.ClsIFACPersonne
    {
        
        public ClsIFACPersonneClient()
        {
        }
        
        public ClsIFACPersonneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACPersonneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACPersonneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACPersonneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOPersonne> SelectAllPersonne()
        {
            return base.Channel.SelectAllPersonne();
        }
        
        public System.IAsyncResult BeginSelectAllPersonne(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllPersonne(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOPersonne> EndSelectAllPersonne(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllPersonne(result);
        }
    }
}
