//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACLivre_Auteur", ConfigurationName="Bibliotheque.Proxies.ClsIFACLivre_Auteur")]
    public interface ClsIFACLivre_Auteur
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACLivre_Auteur/ClsIFACLivre_Auteur/SelectAllLivreAuteur", ReplyAction="COUCHEIFAC/ClsIFACLivre_Auteur/ClsIFACLivre_Auteur/SelectAllLivreAuteurResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOLivre_Auteur> SelectAllLivreAuteur();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACLivre_Auteur/ClsIFACLivre_Auteur/SelectAllLivreAuteur", ReplyAction="COUCHEIFAC/ClsIFACLivre_Auteur/ClsIFACLivre_Auteur/SelectAllLivreAuteurResponse")]
        System.IAsyncResult BeginSelectAllLivreAuteur(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOLivre_Auteur> EndSelectAllLivreAuteur(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACLivre_AuteurChannel : Bibliotheque.Proxies.ClsIFACLivre_Auteur, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACLivre_AuteurClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACLivre_Auteur>, Bibliotheque.Proxies.ClsIFACLivre_Auteur
    {
        
        public ClsIFACLivre_AuteurClient()
        {
        }
        
        public ClsIFACLivre_AuteurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACLivre_AuteurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACLivre_AuteurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACLivre_AuteurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOLivre_Auteur> SelectAllLivreAuteur()
        {
            return base.Channel.SelectAllLivreAuteur();
        }
        
        public System.IAsyncResult BeginSelectAllLivreAuteur(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllLivreAuteur(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOLivre_Auteur> EndSelectAllLivreAuteur(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllLivreAuteur(result);
        }
    }
}
