//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACEtat", ConfigurationName="Bibliotheque.Proxies.ClsIFACEtat")]
    public interface ClsIFACEtat
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACEtat/ClsIFACEtat/SelectAllEtat", ReplyAction="COUCHEIFAC/ClsIFACEtat/ClsIFACEtat/SelectAllEtatResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOEtat> SelectAllEtat();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACEtat/ClsIFACEtat/SelectAllEtat", ReplyAction="COUCHEIFAC/ClsIFACEtat/ClsIFACEtat/SelectAllEtatResponse")]
        System.IAsyncResult BeginSelectAllEtat(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOEtat> EndSelectAllEtat(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACEtatChannel : Bibliotheque.Proxies.ClsIFACEtat, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACEtatClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACEtat>, Bibliotheque.Proxies.ClsIFACEtat
    {
        
        public ClsIFACEtatClient()
        {
        }
        
        public ClsIFACEtatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACEtatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACEtatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACEtatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOEtat> SelectAllEtat()
        {
            return base.Channel.SelectAllEtat();
        }
        
        public System.IAsyncResult BeginSelectAllEtat(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllEtat(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOEtat> EndSelectAllEtat(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllEtat(result);
        }
    }
}
