//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACGenre", ConfigurationName="Bibliotheque.Proxies.ClsIFACGenre")]
    public interface ClsIFACGenre
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACGenre/ClsIFACGenre/SelectAllGenre", ReplyAction="COUCHEIFAC/ClsIFACGenre/ClsIFACGenre/SelectAllGenreResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOGenre> SelectAllGenre();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACGenre/ClsIFACGenre/SelectAllGenre", ReplyAction="COUCHEIFAC/ClsIFACGenre/ClsIFACGenre/SelectAllGenreResponse")]
        System.IAsyncResult BeginSelectAllGenre(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOGenre> EndSelectAllGenre(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACGenreChannel : Bibliotheque.Proxies.ClsIFACGenre, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACGenreClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACGenre>, Bibliotheque.Proxies.ClsIFACGenre
    {
        
        public ClsIFACGenreClient()
        {
        }
        
        public ClsIFACGenreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACGenreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACGenreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACGenreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOGenre> SelectAllGenre()
        {
            return base.Channel.SelectAllGenre();
        }
        
        public System.IAsyncResult BeginSelectAllGenre(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllGenre(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOGenre> EndSelectAllGenre(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllGenre(result);
        }
    }
}
