//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACBiblio", ConfigurationName="Bibliotheque.Proxies.ClsIFACBiblio")]
    public interface ClsIFACBiblio
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACBiblio/ClsIFACBiblio/SelectAllBiblio", ReplyAction="COUCHEIFAC/ClsIFACBiblio/ClsIFACBiblio/SelectAllBiblioResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOBiblio> SelectAllBiblio();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACBiblio/ClsIFACBiblio/SelectAllBiblio", ReplyAction="COUCHEIFAC/ClsIFACBiblio/ClsIFACBiblio/SelectAllBiblioResponse")]
        System.IAsyncResult BeginSelectAllBiblio(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOBiblio> EndSelectAllBiblio(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACBiblioChannel : Bibliotheque.Proxies.ClsIFACBiblio, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACBiblioClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACBiblio>, Bibliotheque.Proxies.ClsIFACBiblio
    {
        
        public ClsIFACBiblioClient()
        {
        }
        
        public ClsIFACBiblioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACBiblioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACBiblioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACBiblioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOBiblio> SelectAllBiblio()
        {
            return base.Channel.SelectAllBiblio();
        }
        
        public System.IAsyncResult BeginSelectAllBiblio(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllBiblio(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOBiblio> EndSelectAllBiblio(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllBiblio(result);
        }
    }
}
