//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACReservation", ConfigurationName="Bibliotheque.Proxies.ClsIFACReservation")]
    public interface ClsIFACReservation
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectAllReservation", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectAllReservationResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOReservation> SelectAllReservation();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectAllReservation", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectAllReservationResponse")]
        System.IAsyncResult BeginSelectAllReservation(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOReservation> EndSelectAllReservation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/Reserver", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/ReserverResponse")]
        COUCHEBO.ClsBOReservation Reserver(string ISBN, int Lecteur_ID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/Reserver", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/ReserverResponse")]
        System.IAsyncResult BeginReserver(string ISBN, int Lecteur_ID, System.AsyncCallback callback, object asyncState);
        
        COUCHEBO.ClsBOReservation EndReserver(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservHistoriqueByUtilisat" +
            "eur", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservHistoriqueByUtilisat" +
            "eurResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOReservation> SelectReservHistoriqueByUtilisateur(int Lecteur_ID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservHistoriqueByUtilisat" +
            "eur", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservHistoriqueByUtilisat" +
            "eurResponse")]
        System.IAsyncResult BeginSelectReservHistoriqueByUtilisateur(int Lecteur_ID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOReservation> EndSelectReservHistoriqueByUtilisateur(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservEnCoursByUtilisateur" +
            "", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservEnCoursByUtilisateur" +
            "Response")]
        System.Collections.Generic.List<COUCHEBO.ClsBOReservation> SelectReservEnCoursByUtilisateur(int Lecteur_ID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservEnCoursByUtilisateur" +
            "", ReplyAction="COUCHEIFAC/ClsIFACReservation/ClsIFACReservation/SelectReservEnCoursByUtilisateur" +
            "Response")]
        System.IAsyncResult BeginSelectReservEnCoursByUtilisateur(int Lecteur_ID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOReservation> EndSelectReservEnCoursByUtilisateur(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACReservationChannel : Bibliotheque.Proxies.ClsIFACReservation, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACReservationClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACReservation>, Bibliotheque.Proxies.ClsIFACReservation
    {
        
        public ClsIFACReservationClient()
        {
        }
        
        public ClsIFACReservationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACReservationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACReservationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACReservationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOReservation> SelectAllReservation()
        {
            return base.Channel.SelectAllReservation();
        }
        
        public System.IAsyncResult BeginSelectAllReservation(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllReservation(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOReservation> EndSelectAllReservation(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllReservation(result);
        }
        
        public COUCHEBO.ClsBOReservation Reserver(string ISBN, int Lecteur_ID)
        {
            return base.Channel.Reserver(ISBN, Lecteur_ID);
        }
        
        public System.IAsyncResult BeginReserver(string ISBN, int Lecteur_ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginReserver(ISBN, Lecteur_ID, callback, asyncState);
        }
        
        public COUCHEBO.ClsBOReservation EndReserver(System.IAsyncResult result)
        {
            return base.Channel.EndReserver(result);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOReservation> SelectReservHistoriqueByUtilisateur(int Lecteur_ID)
        {
            return base.Channel.SelectReservHistoriqueByUtilisateur(Lecteur_ID);
        }
        
        public System.IAsyncResult BeginSelectReservHistoriqueByUtilisateur(int Lecteur_ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectReservHistoriqueByUtilisateur(Lecteur_ID, callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOReservation> EndSelectReservHistoriqueByUtilisateur(System.IAsyncResult result)
        {
            return base.Channel.EndSelectReservHistoriqueByUtilisateur(result);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOReservation> SelectReservEnCoursByUtilisateur(int Lecteur_ID)
        {
            return base.Channel.SelectReservEnCoursByUtilisateur(Lecteur_ID);
        }
        
        public System.IAsyncResult BeginSelectReservEnCoursByUtilisateur(int Lecteur_ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectReservEnCoursByUtilisateur(Lecteur_ID, callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOReservation> EndSelectReservEnCoursByUtilisateur(System.IAsyncResult result)
        {
            return base.Channel.EndSelectReservEnCoursByUtilisateur(result);
        }
    }
}
