//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COUCHEIFAC/ClsIFACAuteur", ConfigurationName="Bibliotheque.Proxies.ClsIFACAuteur")]
    public interface ClsIFACAuteur
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/SelectAllAuteur", ReplyAction="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/SelectAllAuteurResponse")]
        System.Collections.Generic.List<COUCHEBO.ClsBOAuteur> SelectAllAuteur();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/SelectAllAuteur", ReplyAction="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/SelectAllAuteurResponse")]
        System.IAsyncResult BeginSelectAllAuteur(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<COUCHEBO.ClsBOAuteur> EndSelectAllAuteur(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/AddAuteur", ReplyAction="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/AddAuteurResponse")]
        COUCHEBO.ClsBOAuteur AddAuteur(string Nom, string Prenom);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/AddAuteur", ReplyAction="COUCHEIFAC/ClsIFACAuteur/ClsIFACAuteur/AddAuteurResponse")]
        System.IAsyncResult BeginAddAuteur(string Nom, string Prenom, System.AsyncCallback callback, object asyncState);
        
        COUCHEBO.ClsBOAuteur EndAddAuteur(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClsIFACAuteurChannel : Bibliotheque.Proxies.ClsIFACAuteur, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClsIFACAuteurClient : System.ServiceModel.ClientBase<Bibliotheque.Proxies.ClsIFACAuteur>, Bibliotheque.Proxies.ClsIFACAuteur
    {
        
        public ClsIFACAuteurClient()
        {
        }
        
        public ClsIFACAuteurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ClsIFACAuteurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACAuteurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ClsIFACAuteurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOAuteur> SelectAllAuteur()
        {
            return base.Channel.SelectAllAuteur();
        }
        
        public System.IAsyncResult BeginSelectAllAuteur(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSelectAllAuteur(callback, asyncState);
        }
        
        public System.Collections.Generic.List<COUCHEBO.ClsBOAuteur> EndSelectAllAuteur(System.IAsyncResult result)
        {
            return base.Channel.EndSelectAllAuteur(result);
        }
        
        public COUCHEBO.ClsBOAuteur AddAuteur(string Nom, string Prenom)
        {
            return base.Channel.AddAuteur(Nom, Prenom);
        }
        
        public System.IAsyncResult BeginAddAuteur(string Nom, string Prenom, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginAddAuteur(Nom, Prenom, callback, asyncState);
        }
        
        public COUCHEBO.ClsBOAuteur EndAddAuteur(System.IAsyncResult result)
        {
            return base.Channel.EndAddAuteur(result);
        }
    }
}
